language: go
sudo: required

services:
- docker

env:
  matrix:
  - DEP_VERSION=0.4.1
  global:
  - secure: Z+HW7TR0bojTLy1SE1IfD9CBVZJZfgBROfCsZm9fleP5pcutc/goxAd2/t/EJLcwt0qNiv+ypzYZn5PyUCLiy6rna0on1LoYeNTqm1dfasbLw+POJvyFpPX5uvuH3LQFkp1I1pzGNcC29yvnLSYc4n6HU6eDDMzQ1jfRXRra51Ss+VK4BVOu2OIUW6qJQ4o2DJ6vUA+zNCDfG17+GYn1ALfHYgcF9ORBfPl07Nb4ZBum6tXcZCIiivHhVYwfFR4ApPq1tAtwm4IVsP9AZZeXAlipyZwwV/2xOxuiUIGdRzA1KrasnQcZl/IppSr9kY4ELm00t4hghEOMsdmGWpc8BaNfYvA43hMxcfbFYUOiblLzB6roRlQj9XWw3rqHOA2CFv/Gyvp9v64CU1eFp0ud/esW8fN/Ern39wujR/rPjPj4X2o53lC2jE6OuL1ySBzXXl87R+WgG5uO3kaOw/aHLlUQVxaT1Uu9GTxHGltEUHCk5PV2nbkYlaPt3J1a1xM1ifQ6pBDV9tKn5F6vrV+2kByuH35uvJib0tdWCLQF9IpRk6YCojf5a4YEYJEN3NiylHVM87za7oLAwVaH6bROP2IEoq0jL7csnI/d8biIQJ2xlF5MuFmLJ7Qrckc6yGGpO5icozsspL2/jtwbt/eoh+FtWGH2t8t8NbgSdkHMub8=
  - secure: B38A60dVe6PN9cir//OVXj7RSdTckmjnigGgz0oawNAZ+OfL0R6JN85edcqxQG5EQtHeSrXBC24w/nFO5pdH9GlG8EqKhwceLMDUEFwas79JfN08LTNkDBWYm7qtISC9grHbVeaSEEt4PlYj3AmKDOOlKGM0ZiffHZg67egOWWvlM1U4REONP70WQOYQiYHY5TqnNTkIESWfBKTGsBDGnkgOLxdAzAsvNUF1hf40ZuBNBIAKdnSRGQEmGmMy4/qIS8enVGC8MOByPgMBm3C2vAavVctp204+ArXnQr8oaycnZeIkeOn8WDhBfCQd9OqaqYieVrkYbbZ4m6atMCzfjixVpaH43WwtRCD7HxTpSpqkv0txMi9z2CzAFZl7KoslSXCaU3CO6kGOIgLLFyYk+yzdCgCDrDhTYESlJgyMOBYM3wcP4fayTjyz60kdrD1XsciZgVyBJ2Qg1Vu3k5+jW3sTidm6D1EkWVQi9ToEF5pDncRRzIh2kNXXcoeocdk3DvvvAfnC/RfW3kKZVvLYea87mJd1nmOMFYqylbgK3EJ62tlKiiZpSx0ukA8tEAY5pY5qPCRi3wAQYZTWSoXJIgW/QcYXlXJ1RgXJZOkTUaS+zRcvMeAL8PvC4aORBltilGzHcyhtk4fp5MZX4KaAzAGWN8T+9xfL51JFE2m9xns=

go:
- 1.10.2

script:
- export TAG=`if [ $TRAVIS_BRANCH == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export REPO=doitintl/kuberbs
- docker build -t $REPO:$TAG -f Dockerfile .

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- echo $TAG
- docker push $REPO:$TAG
notifications:
  email: false
